<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_All</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>aa2d9adf-dd1f-4bca-a043-9a524769c979</testSuiteGuid>
   <testCaseLink>
      <guid>cf2b3c75-8967-4828-943f-18debe7c6da0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Failed/TC_Failed_checkout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f9463b25-3285-485f-954f-38f71c7d3a62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Success_checkout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e0e018d1-de91-4f22-9577-dfb117ef1c48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Success_Popup</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2fe928d1-40f6-4da3-9d8d-2978cfee2351</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6e8778d-c921-4398-aa21-9476d1f3ec7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7058fd1-8ce5-43a6-8bfd-b3871c2a9224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95536aa5-239c-4aec-a7e8-701f293afdb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9bf7742-ca59-42d0-9b5a-0e0934ce9358</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03c787fb-6b4e-46b7-be89-2d7f6a32da4e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1ce8169d-1b54-425a-8929-bf44ec614ea6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Success_Payment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6550169-869d-4dab-b9ef-d643e9969624</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57aed25a-1fb0-47c3-99bd-14b0846af380</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f5bd44e-57ed-4b3d-a791-e8e7709b8147</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Success_Issue_bank</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
